services:
  chess-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      # These match the keys in your application.properties
      - SERVER_PORT=8080
      - DB_URL=jdbc:postgresql://db-service:5432/chess_db
      - DB_USER=postgres
      - DB_PASSWORD=1424
      - JPA_STRATEGY=update
      - JWT_SECRET=ZuKDHy7kqo6ytelWsPNKje9lweOhKb9MZuKDH6ytelWsPNKje9lweOhKb9M
      - JWT_EXPIRATION=86400000
      - REDIS_HOST=redis-service
      - REDIS_PORT=6379
      - REDIS_PASSWORD=1424
    depends_on:
      - db-service
      - redis-service

  db-service:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=chess_db
      - POSTGRES_PASSWORD=1424
    ports:
      - "5432:5432"

  redis-service:
    image: redis:alpine
    command: redis-server --requirepass 1424
    ports:
      - "6379:6379"