# Server Configuration
server.port=${SERVER_PORT}

# PostgreSQL Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${JPA_STRATEGY}
spring.jpa.show-sql=false

# JWT Configuration
jwt.secret-key=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION}

# Redis Configuration@
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}

# CORS comma-separated list of allowed origins
cors.allowed-origins=${CORS_ORIGINS}

# Logging
logging.level.root=INFO