# 1. DATABASE (POSTGRESQL) CONFIGURATION
spring.datasource.url=jdbc:postgresql://ep-autumn-flower-a1hm9apy.ap-southeast-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_1vUcbetTpX3w

# 2. JPA / HIBERNATE CONFIGURATION
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 3. JWT (SECURITY TOKEN) CONFIGURATION
jwt.secret-key=ZuKDHy7kqo6ytelWsPNKje9lweOhKb9MZuKDH6ytelWsPNKje9lweOhKb9M
jwt.expiration-ms=86400000

# 4. REDIS CONFIGURATION
spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379

#logging.level.root=DEBUG
logging.level.org.springframework.web.socket=DEBUG
logging.level.org.springframework.messaging=DEBUG
logging.level.org.springframework.security=DEBUG
