package app.chess.com.game;

public enum GameStatus {
    ONGOING,
    ABANDONED,
    DRAW_STALEMATE,
    DRAW_INSUFFICIENT_MATERIAL,
    DRAW_FIFTY_MOVE_RULE,
    DRAW_THREEFOLD_REPETITION,
    DRAW_AGREEMENT,
    WON_WHITE_CHECKMATE,
    WON_BLACK_CHECKMATE,
    WON_WHITE_TIMEOUT,
    WON_BLACK_TIMEOUT,
    WON_WHITE_RESIGNATION,
    WON_BLACK_RESIGNATION
}
